const data = {
    products:[
        {
            _id: '1',
            name: 'milk and honey',
            caregory: 'fiction',
            image: './images/product3.jpg',
            price: 299,
            brand: 'one',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'little black book',
            caregory: 'fiction',
            image: './images/product2.jpg',
            price: 349,
            brand: 'one',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'take the risk',
            caregory: 'fiction',
            image: './images/product1.jpg',
            price: 249,
            brand: 'one',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'milk and honey',
            caregory: 'fiction',
            image: './images/product3.jpg',
            price: 299,
            brand: 'one',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'little black book',
            caregory: 'fiction',
            image: './images/product2.jpg',
            price: 349,
            brand: 'one',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'take the risk',
            caregory: 'fiction',
            image: './images/product1.jpg',
            price: 249,
            brand: 'one',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;